### ISSUE TITLE
cri-docker not compatible with docker-api

### ISSUE THREAD

**Issue by markma85** [cecep-91/upgrade_kubernetes#1]
Hi @cecep-91 ,

Thank you for this wonderful project! I've learnt much from the playbook.

I ran into a small problem, the latest docker version seems not compatible with the cri-docker you put in the `roles/pre_upgrade/files/` folder.
OS: Ubuntu Desktop 24.04
docker-ce & docker-cli version:
```
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.41 (downgraded from 1.47)
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:40:59 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:55:09 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.1.14
  GitCommit:        v1.1.14-0-g2c9f560
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
Playbook failed at step Reload systemd and start cri-docker, the cri-docker daemon service cannot be started. When I check the service logs, it says
 ```
Oct 16 05:36:32 master cri-dockerd[45716]: time="2024-10-16T05:36:32+10:30" level=info msg="Starting cri-dockerd dev (HEAD)"
Oct 16 05:36:32 master cri-dockerd[45716]: time="2024-10-16T05:36:32+10:30" level=info msg="Connecting to docker on the Endpoint unix:///var/run/docker>Oct 16 05:36:32 master cri-dockerd[45716]: time="2024-10-16T05:36:32+10:30" level=info msg="Start docker client with request timeout 0s"
Oct 16 05:36:32 master cri-dockerd[45716]: time="2024-10-16T05:36:32+10:30" level=fatal msg="docker API version is older than 1.42.0"
```
I assume you used the latest cri-dockerd, requires docker API 1.42+, but latest docker with my OS release docker API version is 1.41. I looked up the cri-dockerd repo, but not found version compatible table.

Could you tell me how did you get the cri-dockerd, from which release file? I want to pull an older version of the file to have a try. Thank you!

**Comment by cecep-91** [comment]
Sorry for the trouble! I think the cri-dockerd I use is the latest release from the repo. Maybe your problem is that You haven’t added the official docker repo yet, so ubuntu is pulling from its own repo, which is a bit outdated. That’s why you’re stuck with Docker API version 1.41, and it’s not working with the latest cri-dockerd.

For temporary solution, try adding the official docker repo manually. I’ll make the changes in future commit.

**Comment by cecep-91** [comment]
Just question, what is the latest docker version from command
```
apt policy docker-ce
```
And did you perhaps hold your docker package?

**Comment by markma85** [comment]
Yes I should have installed the latest docker Ubuntu noble release version.
```
root@master:~# apt policy docker-ce
docker-ce:
  Installed: 5:27.3.1-1~ubuntu.24.04~noble
  Candidate: 5:27.3.1-1~ubuntu.24.04~noble
  Version table:
 *** 5:27.3.1-1~ubuntu.24.04~noble 500
        500 https://download.docker.com/linux/ubuntu noble/stable amd64 Packages
        100 /var/lib/dpkg/status
     5:27.3.0-1~ubuntu.24.04~noble 500
        500 https://download.docker.com/linux/ubuntu noble/stable amd64 Packages
     5:27.2.1-1~ubuntu.24.04~noble 500
        500 https://download.docker.com/linux/ubuntu noble/stable amd64 Packages
     5:27.2.0-1~ubuntu.24.04~noble 500
        500 https://download.docker.com/linux/ubuntu noble/stable amd64 Packages
     5:27.1.2-1~ubuntu.24.04~noble 500
        500 https://download.docker.com/linux/ubuntu noble/stable amd64 Packages
     5:27.1.1-1~ubuntu.24.04~noble 500
```
May I know from which [release asset](https://github.com/Mirantis/cri-dockerd/releases/tag/v0.3.15) you got the cri-docker file? I downloaded this one [cri-dockerd-0.3.15.arm64.tgz](https://github.com/Mirantis/cri-dockerd/releases/download/v0.3.15/cri-dockerd-0.3.15.arm64.tgz) but the file size is 44.3Mb, the one in your repo is 65Mb.

**Comment by cecep-91** [comment]
Docker version 27.3.1 should be able to run cri-dockerd.

I build the cri-dockerd my self with go1.21.5, not from the release asset. Maybe from one of the latest 3 commit of the repo.

**Comment by markma85** [comment]
Here are what I did during the 2 days:
1. I pulled the cri-dockerd-0.3.14 version source code and built on my machine, used the generated cri-dockerd and successfully resolved the issue, with your script I have upgraded from 1.23 to 1.26 like a charm.
2. After used the cluster for a while, I messed up with the calico network and k8s's core-dns, so I teared down the cluster and re-installed everything. Once installed docker, I realized I must have done something wrong last time, this time docker ce API version is 1.47.
```
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:40:59 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:40:59 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.22
  GitCommit:        7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc:
  Version:          1.1.14
  GitCommit:        v1.1.14-0-g2c9f560
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Thank you for the help! There should be no issue to your playbook scripts and the cri-dockerd file. Can close this thread.
